//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteEDD.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.WebServicesSoap")]
    public interface WebServicesSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/log", ReplyAction="*")]
        ClienteEDD.ServiceReference2.logResponse log(ClienteEDD.ServiceReference2.logRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/log", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteEDD.ServiceReference2.logResponse> logAsync(ClienteEDD.ServiceReference2.logRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="log", Namespace="http://tempuri.org/", Order=0)]
        public ClienteEDD.ServiceReference2.logRequestBody Body;
        
        public logRequest() {
        }
        
        public logRequest(ClienteEDD.ServiceReference2.logRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class logRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pw;
        
        public logRequestBody() {
        }
        
        public logRequestBody(string nombre, string pw) {
            this.nombre = nombre;
            this.pw = pw;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteEDD.ServiceReference2.logResponseBody Body;
        
        public logResponse() {
        }
        
        public logResponse(ClienteEDD.ServiceReference2.logResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class logResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool logResult;
        
        public logResponseBody() {
        }
        
        public logResponseBody(bool logResult) {
            this.logResult = logResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServicesSoapChannel : ClienteEDD.ServiceReference2.WebServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServicesSoapClient : System.ServiceModel.ClientBase<ClienteEDD.ServiceReference2.WebServicesSoap>, ClienteEDD.ServiceReference2.WebServicesSoap {
        
        public WebServicesSoapClient() {
        }
        
        public WebServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteEDD.ServiceReference2.logResponse ClienteEDD.ServiceReference2.WebServicesSoap.log(ClienteEDD.ServiceReference2.logRequest request) {
            return base.Channel.log(request);
        }
        
        public bool log(string nombre, string pw) {
            ClienteEDD.ServiceReference2.logRequest inValue = new ClienteEDD.ServiceReference2.logRequest();
            inValue.Body = new ClienteEDD.ServiceReference2.logRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.pw = pw;
            ClienteEDD.ServiceReference2.logResponse retVal = ((ClienteEDD.ServiceReference2.WebServicesSoap)(this)).log(inValue);
            return retVal.Body.logResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteEDD.ServiceReference2.logResponse> ClienteEDD.ServiceReference2.WebServicesSoap.logAsync(ClienteEDD.ServiceReference2.logRequest request) {
            return base.Channel.logAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteEDD.ServiceReference2.logResponse> logAsync(string nombre, string pw) {
            ClienteEDD.ServiceReference2.logRequest inValue = new ClienteEDD.ServiceReference2.logRequest();
            inValue.Body = new ClienteEDD.ServiceReference2.logRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.pw = pw;
            return ((ClienteEDD.ServiceReference2.WebServicesSoap)(this)).logAsync(inValue);
        }
    }
}
